config/routes.rb
Rails.application.routes.draw do
  resources :workflows

  resources :tasks

  resources :actions

  resources :states
  resources :states_assigns

  resources :leads

  resources :payments

  root 'payments#index'

end

app/models/states_assign.rb
class StatesAssign < ActiveRecord::Base
  belongs_to :state
end

app/controllers/states_assigns_controller.rb
class StatesAssignsController < ApplicationController
  before_action :set_states_assign, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states_assigns = StatesAssign.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @states_assign = StatesAssign.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @states_assign = StatesAssign.new(states_assign_params)

    respond_to do |format|
      if @states_assign.save
        format.html { redirect_to @states_assign, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @states_assign }
        "#{@states_assign.assigned_to}StateMachine".constantize.state @states_assign.state.name.to_sym

        puts '##############################'
        puts  LeadStateMachine.states
        puts '##############################'

      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      "#{@states_assign.assigned_to}StateMachine".constantize.states.delete(@states_assign.state.name)
      if @states_assign.update(states_assign_params)
        format.html { redirect_to @states_assign, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @states_assign }
        "#{@states_assign.assigned_to}StateMachine".constantize.state @states_assign.state.name.to_sym

        puts '##############################'
        puts  LeadStateMachine.states
        puts '##############################'

        puts '##############################'
        puts  PaymentStateMachine.states
        puts '##############################'


      else
        format.html { render :edit }
        format.json { render json: @states_assign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    "#{@states_assign.assigned_to}StateMachine".constantize.states.delete(@states_assign.state.name)
    @states_assign.destroy

    puts '##############################'
    puts  LeadStateMachine.states
    puts '##############################'

    respond_to do |format|
      format.html { redirect_to states_assigns_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_states_assign
    @states_assign = StatesAssign.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def states_assign_params
    params.require(:states_assign).permit(:assigned_to, :state_id)
  end
end

app/views/states_assigns/_form.html.erb
<%= form_for(@states_assign) do |f| %>
  <% if @states_assign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@states_assign.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @states_assign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :assigned_to %><br>
    <%= f.text_field :assigned_to, value: 'Lead' %>
  </div>

  <div class="field">
    <%= collection_select(:states_assign, :state_id, State.all, :id, :name, :prompt => 'Please Select a State')%>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states_assigns/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @states_assign %> |
<%= link_to 'Back', states_assigns_path %>

app/views/states_assigns/index.html.erb
<h1>Listing states assignments</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Assigned To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states_assigns.each do |states_assign| %>
      <tr>
        <td><%= states_assign.state.name %></td>
        <td><%= states_assign.assigned_to %></td>
        <td><%= link_to 'Show', states_assign %></td>
        <td><%= link_to 'Edit', edit_states_assign_path(states_assign) %></td>
        <td><%= link_to 'Destroy', states_assign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignment', new_states_assign_path %>

app/views/states_assigns/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_assigns_path %>

app/views/states_assigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @states_assign.state.name %>
</p>

<%= link_to 'Edit', edit_states_assign_path(@states_assign) %> |
<%= link_to 'Back', states_assigns_path %>